### ISSUE TITLE
Failure when enabling app for Nextcloud 19

### ISSUE THREAD

**Issue by aszlig** [thrillfall/nextcloud-gpodder#6]
When using `occ app:enable` on Nextcloud 19, you'll get the following error:

```
Error: Class 'Doctrine\DBAL\Types\Types' not found in .../apps/gpoddersync/lib/Migration/Version0001Date20210520063113.php:39
Stack trace:
#0 .../lib/private/DB/MigrationService.php(478): OCA\GPodderSync\Migration\Version0001Date20210520063113->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 .../lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('0001Date2021052...', false)
#2 .../lib/private/Installer.php(157): OC\DB\MigrationService->migrate()
#3 .../core/Command/App/Enable.php(122): OC\Installer->installApp('gpoddersync', false)
#4 .../core/Command/App/Enable.php(92): OC\Core\Command\App\Enable->enableApp('gpoddersync', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 .../3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 .../3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 .../3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 .../3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 .../lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 .../console.php(85): OC\Console\Application->run()
#11 .../occ(11): require_once('...
```

This has been found as part of an automated test. I do not run Nextcloud 19 anywhere, so I can't provide more information other than the [full test log](https://headcounter.org/hydra/log/2h2mmpl041nm52nw5wdk69x8mv59964d-vm-test-run-nextcloud-upgrade.drv) and its [source code](https://github.com/aszlig/avonc/blob/74a8d8c525885a3790839392fb1d7d79c6ccf006/tests/upgrade.nix).

Since the app is rather new, I'd suggest to just remove support for Nextcloud 19, since NC19 has already reached its [end of life](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).

**Comment by thrillfall** [comment]
Thank you for catching this. I'll increase minimum supported version

**Comment by thrillfall** [comment]
1.0.5 with min-version: 20 released.
